/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaCliente;
import ControladorCliente.ControladorCliente;
import javax.swing.JOptionPane;
/**
 *
 * @author invitado
 */
public class VistaCliente extends javax.swing.JFrame {
    ControladorCliente miControlCliente;
    
    /**
     * Creates new form Principal
     */
    public VistaCliente() {
        miControlCliente = new ControladorCliente();
        miControlCliente.ejecutarCliente();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        buttonAddBook = new javax.swing.JButton();
        buttonDeleteBook = new javax.swing.JButton();
        buttonFindBook = new javax.swing.JButton();
        buttonEditBook = new javax.swing.JButton();
        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCliente = new javax.swing.JMenu();
        cerrarConexion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        buttonAddBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/addBookButton.png"))); // NOI18N
        buttonAddBook.setText("Agregar");
        buttonAddBook.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonAddBook.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddBookActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 43, 10, 0);
        jPanel1.add(buttonAddBook, gridBagConstraints);

        buttonDeleteBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/deleteBookButton.png"))); // NOI18N
        buttonDeleteBook.setText("Eliminar");
        buttonDeleteBook.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonDeleteBook.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonDeleteBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteBookActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 10, 0);
        jPanel1.add(buttonDeleteBook, gridBagConstraints);

        buttonFindBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/findBookButton.png"))); // NOI18N
        buttonFindBook.setText("Consultar");
        buttonFindBook.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonFindBook.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonFindBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFindBookActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 10, 0);
        jPanel1.add(buttonFindBook, gridBagConstraints);

        buttonEditBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/editBookButton.png"))); // NOI18N
        buttonEditBook.setText("Editar");
        buttonEditBook.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonEditBook.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonEditBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditBookActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 10, 48);
        jPanel1.add(buttonEditBook, gridBagConstraints);

        jTabbedPane1.addTab("Libros", jPanel1);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        menuCliente.setText("Opciones");

        cerrarConexion.setText("Cerrar cliente");
        cerrarConexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarConexionActionPerformed(evt);
            }
        });
        menuCliente.add(cerrarConexion);

        jMenuBar1.add(menuCliente);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(desktopPane)
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktopPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddBookActionPerformed
        InternalAddBook add = new InternalAddBook(miControlCliente);
        this.desktopPane.add(add);
        add.setVisible(true);
    }//GEN-LAST:event_buttonAddBookActionPerformed

    private void buttonDeleteBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteBookActionPerformed
        InternalDeleteBook del = new InternalDeleteBook(miControlCliente);
        this.desktopPane.add(del);
        del.setVisible(true);
    }//GEN-LAST:event_buttonDeleteBookActionPerformed

    private void buttonFindBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFindBookActionPerformed
        InternalFindBook find = new InternalFindBook(miControlCliente);
        this.desktopPane.add(find);
        find.setVisible(true);
    }//GEN-LAST:event_buttonFindBookActionPerformed

    private void cerrarConexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarConexionActionPerformed
        String msg = miControlCliente.cerrarConexion();
        JOptionPane.showMessageDialog(this, msg);
    }//GEN-LAST:event_cerrarConexionActionPerformed

    private void buttonEditBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditBookActionPerformed
        InternalEditBook edit = new InternalEditBook(miControlCliente);
        this.desktopPane.add(edit);
        edit.setVisible(true);
    }//GEN-LAST:event_buttonEditBookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddBook;
    private javax.swing.JButton buttonDeleteBook;
    private javax.swing.JButton buttonEditBook;
    private javax.swing.JButton buttonFindBook;
    private javax.swing.JMenuItem cerrarConexion;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenu menuCliente;
    // End of variables declaration//GEN-END:variables
}
